#!/usr/bin/env bash
# deploy.sh -- bring the SmartHub/Anton Docker stack up on EC2 or locally.
#
# This captures the runtime steps that made the stack work end-to-end:
#   * point the browser-facing Prefect UI at the right API host (public IP on
#     EC2, localhost locally) -- otherwise the UI calls 127.0.0.1 and a remote
#     browser can't reach it;
#   * guarantee the `mlflow` Postgres database exists (mlflow-ui crash-loops and
#     hammers Postgres with reconnects without it);
#   * start prefect-server, wait for it to report healthy, then bring the worker
#     up (its depends_on:service_healthy gate keeps it 'Created' until then).
#
# The compose files themselves already carry the other fixes (Postgres
# max_connections=300, prefect-server SQLAlchemy pool caps, the /api/health
# healthcheck, shap/slo healthcheck disable). This script just orchestrates.
#
# Usage:
#   ./deploy.sh                       # auto-detect: EC2 if instance metadata is
#                                     #   reachable, else local
#   ./deploy.sh local                 # force local  -> UI API at localhost:4200
#   ./deploy.sh ec2                   # force EC2     -> UI API at <public-ip>:4200
#   PREFECT_UI_HOST=1.2.3.4 ./deploy.sh ec2   # pin the host used in the UI URL
#                                             #   (use your Elastic IP / DNS)
#
# Safe to re-run.

set -euo pipefail
cd "$(dirname "$0")"

PREFECT_FILE="docker-compose.prefect.yml"
LOCAL_FILE="docker-compose.local.yml"
UIURL_FILE="docker-compose.uiurl.yml"   # generated below

# ---------------------------------------------------------------------------
# 1. Decide mode + the host the *browser* will use to reach the Prefect API.
# ---------------------------------------------------------------------------
MODE="${1:-auto}"

detect_public_ip() {
  # Try IMDSv2 (token) first, fall back to IMDSv1. Empty output => not on EC2.
  local token ip
  token="$(curl -s --max-time 2 -X PUT \
             "http://169.254.169.254/latest/api/token" \
             -H "X-aws-ec2-metadata-token-ttl-seconds: 60" 2>/dev/null || true)"
  if [ -n "$token" ]; then
    ip="$(curl -s --max-time 2 -H "X-aws-ec2-metadata-token: $token" \
            http://169.254.169.254/latest/meta-data/public-ipv4 2>/dev/null || true)"
  else
    ip="$(curl -s --max-time 2 \
            http://169.254.169.254/latest/meta-data/public-ipv4 2>/dev/null || true)"
  fi
  echo "$ip"
}

if [ "$MODE" = "auto" ]; then
  if detect_public_ip | grep -qE '^[0-9]+\.[0-9]+\.'; then MODE="ec2"; else MODE="local"; fi
fi

if [ "$MODE" = "ec2" ]; then
  HOST="${PREFECT_UI_HOST:-$(detect_public_ip)}"
  if [ -z "$HOST" ]; then
    echo "ERROR: could not determine the public IP." >&2
    echo "       Pass it explicitly: PREFECT_UI_HOST=<ip-or-dns> ./deploy.sh ec2" >&2
    exit 1
  fi
else
  HOST="localhost"
fi

UI_API_URL="http://${HOST}:4200/api"
echo ">> mode=${MODE}  PREFECT_UI_API_URL=${UI_API_URL}"

# ---------------------------------------------------------------------------
# 2. Write the UI-URL compose override (no editor needed).
# ---------------------------------------------------------------------------
cat > "$UIURL_FILE" <<EOF
# Generated by deploy.sh -- the browser-facing Prefect API URL.
# Do not edit by hand; re-run ./deploy.sh to regenerate.
services:
  prefect-server:
    environment:
      PREFECT_UI_API_URL: ${UI_API_URL}
EOF

# ---------------------------------------------------------------------------
# 2b. Serve tuning override (uvicorn workers + single-threaded math so worker
#     count is the only parallelism knob -- avoids BLAS/OpenMP oversubscription).
#     Override at runtime: SERVE_WORKERS=6 ./deploy.sh
# ---------------------------------------------------------------------------
TUNE_FILE="docker-compose.tune.yml"
SERVE_WORKERS="${SERVE_WORKERS:-4}"
cat > "$TUNE_FILE" <<EOF
# Generated by deploy.sh -- serve concurrency tuning. Re-run to regenerate.
services:
  serve:
    environment:
      SERVE_WORKERS: "${SERVE_WORKERS}"
      OMP_NUM_THREADS: "1"
      OPENBLAS_NUM_THREADS: "1"
      MKL_NUM_THREADS: "1"
EOF
echo ">> SERVE_WORKERS=${SERVE_WORKERS} (math threads pinned to 1)"

COMPOSE=(-f "$PREFECT_FILE" -f "$LOCAL_FILE" -f "$UIURL_FILE" -f "$TUNE_FILE")

# ---------------------------------------------------------------------------
# 3. Bring the stack up (builds from source via the local overlay).
# ---------------------------------------------------------------------------
echo ">> docker compose up -d (build + start)"
docker compose "${COMPOSE[@]}" up -d

# ---------------------------------------------------------------------------
# 4. Ensure the `mlflow` database exists (idempotent), then nudge mlflow-ui.
# ---------------------------------------------------------------------------
echo ">> ensuring 'mlflow' database exists"
docker exec prefect-postgres sh -c \
  "psql -U prefect -tc \"SELECT 1 FROM pg_database WHERE datname='mlflow'\" | grep -q 1 \
   || psql -U prefect -c 'CREATE DATABASE mlflow'"
docker restart smarthub-mlflow-ui >/dev/null 2>&1 || true

# ---------------------------------------------------------------------------
# 5. Wait for prefect-server health, then (re)start so the worker gate opens.
# ---------------------------------------------------------------------------
echo -n ">> waiting for prefect-server to be healthy "
for _ in $(seq 1 36); do
  status="$(docker inspect -f '{{.State.Health.Status}}' prefect-server 2>/dev/null || echo missing)"
  [ "$status" = "healthy" ] && { echo " -> healthy"; break; }
  echo -n "."
  sleep 5
done
if [ "$(docker inspect -f '{{.State.Health.Status}}' prefect-server 2>/dev/null || true)" != "healthy" ]; then
  echo
  echo "WARN: prefect-server not healthy yet. Check: docker logs prefect-server --tail 30" >&2
fi

# Second pass: now that the server is healthy, the worker's
# depends_on:service_healthy gate opens and it leaves 'Created'.
docker compose "${COMPOSE[@]}" up -d

echo
echo ">> done. Prefect UI: http://${HOST}:4200"
docker compose "${COMPOSE[@]}" ps
