schema_version: 1
lead_type_id: 1
parameter_version: params_774d2073728679328538335f
model_settings:
  model_type: lightgbm
  model_parameters:
    verbosity: -1
    n_jobs: 1
    subsample_freq: 1
    num_leaves: 98
    max_depth: 6
    learning_rate: 0.04502215590015161
    min_child_samples: 77
    subsample: 0.9045809768629978
    colsample_bytree: 0.6034166825746311
    reg_alpha: 0.000823948019049902
    reg_lambda: 0.00029305965020131757
  calibration:
    enabled: false
created_at: null
code_version: null
hpo_run_id: null
hpo_mlflow_run_id: null
hpo_mlflow_tracking_uri: null
data: null
approved_training_run_id: null
production_model_version: null
initialized_from_bootstrap: false
